config/routes.rb
SampleApp::Application.routes.draw do
  root to: 'static_pages#home'
  
  get "/home", to: 'static_pages#home', as: :home
  get "/help", to: 'static_pages#help', as: :help
  get "/about", to: 'static_pages#about', as: :about
  get "/contact", to: 'static_pages#contact', as: :contact
  
  resources :users do
    member do
      get 'following', 'followers'
    end
    
    collection do
      get 'new_password', 'new_password'
      post 'reset_password', 'reset_password'
    end
  end
  
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:edit, :update]
  
  get "/signup", to: 'users#new', as: :signup
  get '/signin', to: 'sessions#new', as: :signin
  delete '/signout', to: 'sessions#destroy', as: :signout

  

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :activation_token
  
  has_many :microposts, dependent: :destroy
  has_many :relationships, foreign_key: :follower_id, dependent: :destroy
  has_many :followed_users, through: :relationships, source: :followed
  has_many :reversed_relationships, foreign_key: :followed_id,
           class_name: 'Relationship', dependent: :destroy
  has_many :followers, through: :reversed_relationships, source: :follower
  
  before_save { email.downcase! }
  before_create :create_remember_token
  before_create :create_activation_digest
  
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\Z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }
  validates :email, uniqueness: { case_sensitive: false } 
  validates :password, length: { minimum: 6 }
  has_secure_password
  
  def feed
    Micropost.from_users_followed_by(self)
  end
  
  def following?(other_user)
    relationships.find_by followed_id: other_user.id
  end
  
  def follow!(other_user)
    relationships.create!(followed_id: other_user.id)
  end
  
  def unfollow!(other_user)
    relationships.find_by(followed_id: other_user.id).destroy
  end
  
  def has_activation_token?(token)
    self.activation_digest == User.digest(token)
  end
  
  def has_reset_token?(token)
    self.password_reset_token == token
  end
  
  def password_expired?
    self.password_reset_expired < Time.zone.now
  end
  
  def self.search(search, page)
    if search
      where("name LIKE ?", "%#{search}%").paginate(page: page)
    else
      paginate(page: page)
    end
  end
  
  def self.new_remember_token
    SecureRandom.urlsafe_base64
  end
  
  def self.digest(token)
    Digest::SHA1.hexdigest(token.to_s)
  end
  
  private
    
    def create_remember_token
      self.remember_token = User.digest(User.new_remember_token)
    end
    
    def create_activation_digest
      self.activation_token = User.new_remember_token
      self.activation_digest = User.digest(activation_token)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signing_in, only: [:index, :edit, :update, :following, :followers]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: :destroy
  before_action :redirect_sign_in_user, only: [:new_password]
  
  def index
    @users = User.search(params[:search], params[:page])
  end
  
  def new
    @user = User.new
  end
  
  def show
    @user = User.find params[:id]
    @microposts = @user.microposts.paginate(page: params[:page])
  end
  
  def create
    @user = User.new(user_param)
    if @user.save
      UserMailer.account_activation(@user).deliver
      flash[:info] = 'Please check your email to activate your account.'
      redirect_to root_path
    else
      render 'new'
    end
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_param)
      flash[:success] = 'Profile updated'
      redirect_to @user
    else
      render 'edit'
    end
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = 'User deleted.'
    redirect_to users_path
  end
  
  def following
    @title = 'Following'
    @user = User.find(params[:id])
    @users = @user.followed_users.paginate(page: params[:page])
    render 'show_follow'
  end
  
  def followers
    @title = 'Followers'
    @user = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end
  
  def new_password
  end
  
  def reset_password
    user = User.find_by_email(params[:email])
    password_reset_token = User.new_remember_token
    user.update_attribute(:password_reset_token, password_reset_token)
    user.update_attribute(:password_reset_expired, 1.day.from_now)
    UserMailer.reset_password(user).deliver
    flash[:info] = 'Please click on the link in your email to reset password'
    redirect_to root_path
  end
  
  private
    def user_param
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
    
    # Before action callback
    def correct_user
      @user = User.find(params[:id])
      redirect_to root_path unless current_user?(@user)
    end
    
    def admin_user
      redirect_to root_path unless current_user.admin?
    end
    
    def redirect_sign_in_user
      redirect_to edit_user_path(current_user) if sign_in?
    end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options={})
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    gravatar_url += "?s=#{options[:size]}" if options[:size]
    image_tag gravatar_url, alt: user.name, class: 'gravatar'
  end
end

app/views/users/_follow.html.erb
<%= form_for current_user.relationships.build(followed_id: @user.id), remote: true do |f| %>
  <div><%= f.hidden_field :followed_id %></div>
  <%= f.submit 'Follow', class: 'btn btn-large btn-primary' %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
    <% if current_user.following?(@user) %>
      <%= render 'unfollow' %>
    <% else %>
      <%= render 'follow' %>
    <% end %>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for current_user.relationships.find_by(followed_id: @user.id),
                              html: { method: :delete }, remote: true do |f| %>
  <%= f.submit 'Unfollow', class: 'btn btn-large' %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 50 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to 'Delete', user, method: :delete, data: { confirm: 'You sure?' } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<%= provide :title, 'Edit user' %>

<h1>Update user profile</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for @user do |f| %>
      <%= render 'shared/error_message', object: f.object %>
      <%= f.label :name %>
      <%= f.text_field :name %>
      
      <%= f.label :email %>
      <%= f.text_field :email %>
      
      <%= f.label :password %>
      <%= f.password_field :password %>
      
      <%= f.label :password_confirmation, 'Confirm Password' %>
      <%= f.password_field :password_confirmation %>
      
      <%= gravatar_for @user %>&nbsp;
      <%= link_to 'Change', 'http://gravatar.com/emails' %>
      
      <%= f.submit 'Save changes', class: 'btn btn-large btn-primary' %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<% provide :title, 'All users' %>

<%= render 'shared/search_form' %>

<h1>
  <%= params[:search].nil? ? 'All users' : 'Search users' %>
</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide :title, 'Sign up' %>
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for @user do |f| %>
      <%= render 'shared/error_message', object: f.object %>
      <%= f.label :name %>
      <%= f.text_field :name %>
      
      <%= f.label :email %>
      <%= f.text_field :email %>
      
      <%= f.label :password %>
      <%= f.password_field :password %>
      
      <%= f.label :password_confirmation, 'Password Confirmation' %>
      <%= f.password_field :password_confirmation %>
      
      <%= f.submit 'Create Account', class: 'btn btn-large btn-primary' %>
    <% end %>
  </div>
</div>

app/views/users/new_password.html.erb
<% provide :title, 'Reset Password' %>

<h1>Reset Password</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_tag reset_password_users_path do %>
      <%= label_tag :email, 'Email' %>
      <%= text_field_tag :email %>
      
      <%= submit_tag 'Send Email', class: 'btn btn-large btn-primary' %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide :title, @user.name %>
<div class="row">
  <aside class="span4">
    <section>
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
    <section>
      <%= render 'shared/stats' %>
    </section>
  </aside>
  <div class="span8">
    <%= render 'follow_form' if sign_in? %>
    <% if @user.microposts.any? %>
      <h3>Microposts (<%= @user.microposts.count %>)</h3>
      <ol class="microposts">
        <%= render @microposts %>
      </ol>
      <%= will_paginate @microposts %>
    <% end %>
  </div>
</div>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="row">
  <aside class="span4">
    <section>
      <%= gravatar_for @user %>
      <h1><%= @user.name %></h1>
      <span><%= link_to "view my profile", @user %></span>
      <span><b>Microposts:</b> <%= @user.microposts.count %></span>
    </section>
    <section>
      <%= render 'shared/stats' %>
      <% if @users.any? %>
        <div class="user_avatars">
          <% @users.each do |user| %>
            <%= link_to gravatar_for(user, size: 30), user %>
          <% end %>
        </div>
      <% end %>
    </section>
  </aside>
  <div class="span8">
    <h3><%= @title %></h3>
    <% if @users.any? %>
      <ul class="users">
        <%= render @users %>
      </ul>
      <%= will_paginate %>
    <% end %>
  </div>
</div>